stages:
  - build
  - package

Build App:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: build
  script:
    - dotnet publish -c Debug -o out
  artifacts:
    paths:
      - out/

Package for Veracode:
  image: ubuntu:latest
  stage: package
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsS https://tools.veracode.com/veracode-cli/install | sh
    - veracode package --source out --output verascan --trust
  artifacts:
    paths:
      - verascan/
